image: alpine:latest

stages:
  - build
  - deploy

# Build APK job
build_apk:
  stage: build
  image: cirrusci/flutter:stable
  before_script:
    - cd shots_studio/
    - flutter pub get
  script:
    - flutter build apk --release
  artifacts:
    paths:
    - build/app/outputs/apk/**/release/*.apk
    expire_in: 1 month

  rules:
    - if: '$CI_COMMIT_TAG'
      when: always    # run automatically on tag
    - when: manual    # allow manual trigger for anything else

# GitLab Pages job
pages:
  stage: deploy
  script:
    - mkdir public
    - cp -r docs/* public
  artifacts:
    paths:
      - public
  only:
    - main
